language: python

env:
  - LAB_ENV=test

install:
  - "pip install -r requirements.txt --use-mirrors --quiet"
  - "pip install -r requirements-test.txt --use-mirrors --quiet"

script: "python tests/integration_tests.py"
