language: python
python: 2.7
install:
    - pip install -r requirements.txt -r requirements-test.txt
    - cp config.py.dist config.py
    - python deploy.py -cdu --db-password=""
script:
    - nosetests labmanager
notifications:
    email:
        - on_success: always
