development:
  engine: mysql
  pymysql: True
  dbname: labmanager
  username: labmanager
  password: labmanager
  host: localhost

test:
  engine: sqlite
  dbname: "test_db.sqlite3"

production:
  driver: pg8000
  engine: postgresql
  pymysql: false
  dbname: some-db-name
  username: labmanager
  password: labmanager
  host: localhost
