standard_urn_admin_roles:
        - Administrator
        - SysAdmin
        - AccountAdmin

permission_status:
        - pending
        - granted
        - denied

authentication_types:
        - oauth1.0
        - basic

user_access_level:
        - admin
        - rlms
        - lms

installed_rlms:
        weblabdeusto:
                - 4.0
